# Generated by Django 3.1.3 on 2020-12-03 17:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_seguindo_tweet'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seguindo',
            unique_together={('de', 'para')},
        ),
    ]
