# Generated by Django 3.1.3 on 2020-12-03 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201203_1739'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
